version: "3.8"
services:
  nginx:
    image: nginx:1.19.2-alpine
    volumes:
      - ./src:/usr/share/nginx/html
      - ./_docker/nginx/templates:/etc/nginx/templates
      - ./_docker/certbot/conf:/etc/letsencrypt
      - ./_docker/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DOMAIN=$DOMAIN
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  # Let's encrypt
  certbot:
    image: certbot/certbot
    volumes:
      - ./_docker/certbot/conf:/etc/letsencrypt
      - ./_docker/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
